### ISSUE TITLE
Ethics of this project

### ISSUE THREAD

**Issue by JanGVoelkel** [chartgerink/2015ori#12]
##### Communality: Scientists openly share findings with colleagues

I think we are doing good for this by using GitHub so that everyone has access to all materials.
##### Universalism: Scientists evaluate research only on its merit, i.e., according to accepted standards of the field.

Does not apply (?)
##### Disinterestedness: Scientists are motivated by the desire for knowledge and discovery, and not by the possibility of personal gain.

I think this is a very difficult point to reach. I am very excited about the potential results of study, but I am also looking forward to the possibility that this ends up in a publication. 
##### Organized Skepticism: Scientists consider all new evidence, hypotheses, theories, and innovations, even those that challenge or contradict their own work.

As far as I know as this is a pretty new topic, I think we are doing fine on this one.
##### Governance: Scientists are responsible for the direction and control of science through governance, self-regulation and peer review.

I think we are doing good on this one. First, everything is transparent so that it is possible to be retracted and controlled by others. Second, I think it is good that each step goes through multiple people so that every one is controlled and exerts control.
##### Quality: Scientists judge each others’ contributions to science primarily on the basis of quality.

Does not apply (?). Also I think it is quite difficult to be free of biases.
##### My conclusion

According to these principles, I think we are doing allright. The biggest aim to reach, I think, is full transpareny and I enjoy the effort we put into this. Otherwise, some of the things are a bit difficult to judge. For instance, I think it is hard to judge as this time if we are incorporating all evidence and whether we put results first, and personal interests second. This might rather become problematic if results are not as we imagine (Btw, I do not have a clear idea about how the results will look like).
##### What to improve

Not sure about this, but one things that came to my mind was the following: As I think Project 1 is rather confirmatory, we could already set up the analysis file for the spreadsheet data in advance.
##### Separating the transcribing

The problem that we may run into if both Chris and Jan do the transcribing is that Chris will be able to identify the participants based on their voice.
What would be possible disadvantages of this? First, the anonymity of the participants is threatened although this is not unavoidable. Second, if participants report practices that suggest that they may have engaged in fraud in the past, Chris might be in a conflict of interest.
What would be advantages of this? We would speed up the transcribing process.
Suggestion: Jan does the transcribing on his own.
##### Potential problems during the transcribing

How can Jan solve problems if he runs into problems during the transcribing (for instance, if he cannot understand what is said)?
He has to figure this out on his own (hear recordings multiple times on different days). At the end, Jan can make a list of all problems he had and sends this to Chris. 
If the problem involves that another person has to hear the segment and Chris decides that it is highly important to solve this issue, Jan shows Chris the respective segment. If it is judges as not being highly important, Jan makes a comment in the transcript file that he was not able to identify the word (or the other problem he had).
#### Identifyable information mentioned in interviews

How are information transcribed that could lead to an identification of the speaker?
If Jan thinks that this is an clearly identifying information, he replaces as much information as needed with "[deleted due to anynomity reasons]".
If Jan is unsure about whether an information is an identifying information, he marks this and asks Chris about it (using the transcript, not the original recording).
Chris doublecheckes every transcript and replaces every potential identifying information with "[deleted due to anynomity reasons]".
If Chris thinks that the replacement of an information by Jan was unnecessary, he discusses the case with Jan. If Chris afterwards still thinks that the replacement was unnecessary, he informs Jan about this and Jan replaces the "[deleted due to anynomity reasons]" with the respective information.

**Comment by chartgerink** [comment]
> Not sure about this, but one things that came to my mind was the following: As I think Project 1 is rather confirmatory, we could already set up the analysis file for the spreadsheet data in advance.

Yes definitely. I need to plan to do this before we get started. That also allows us to preregister.

> Suggestion: Jan does the transcribing on his own.

Okay.

> How can Jan solve problems if he runs into problems during the transcribing (for instance, if he cannot understand what is said)? He has to figure this out on his own (hear recordings multiple times on different days). At the end, Jan can make a list of all problems he had and sends this to Chris. 

Let's make a file where you share the notes from the transcribing process per response, that way we can document potential ambiguities.

> If the problem involves that another person has to hear the segment and Chris decides that it is highly important to solve this issue, Jan shows Chris the respective segment. If it is judges as not being highly important, Jan makes a comment in the transcript file that he was not able to identify the word (or the other problem he had).

That sounds like a good plan. This should also be in the notes then.

> If Jan thinks that this is an clearly identifying information, he replaces as much information as needed with "[deleted due to anynomity reasons]". If Jan is unsure about whether an information is an identifying information, he marks this and asks Chris about it (using the transcript, not the original recording). Chris doublecheckes every transcript and replaces every potential identifying information with "[deleted due to anynomity reasons]". If Chris thinks that the replacement of an information by Jan was unnecessary, he discusses the case with Jan. If Chris afterwards still thinks that the replacement was unnecessary, he informs Jan about this and Jan replaces the "[deleted due to anynomity reasons]" with the respective information.

Great. Ibidem wrt notes.
