### ISSUE TITLE
Qualtrics Quota

### ISSUE THREAD

**Issue by JanGVoelkel** [chartgerink/2015ori#14]
Hey Chris,

I did what you suggested and checked the quota when actually activating the survey. Unfortunately, while the partial responses are recoded, the quota does not increase accordingly. I tried to find out how to fix it but was not able to so far. If you have time or a hunch, maybe you can take a look into it or I will try to fix it on Friday after exams and presentations.

**Comment by chartgerink** [comment]
I just tried it out after activating the survey for a short moment (now not active anymore) and it seems to work nonetheless?

(should not forget to clear the quotum of course)
![screenshot from 2016-10-25 11-57-35](https://cloud.githubusercontent.com/assets/2946344/19681630/6c543f82-9aaa-11e6-94a9-c34b86189557.png)

**Comment by JanGVoelkel** [comment]
I think I solved the problem.

I just made the page with the debriefing that was our last page before the end of survey message so far the end of survey message. So now, if you answer the scheduling question you automatically complete the survey. I don't thinkt this is a pretty solution but I think it should work
