### ISSUE TITLE
Error in Formula of Spreadsheet

### ISSUE THREAD

**Issue by JanGVoelkel** [chartgerink/2015ori#18]
Please take a look at the spreadsheet. The formula for the t-value is incorrect. And there are many undefined hidden rows. I tried to make sense out of it, but I can't really understand how to correct this

**Comment by chartgerink** [comment]
Do you mean it does not work or a specific aspect isn't computed correctly? I get results without problems. Maybe drop by if possible?

**Comment by JanGVoelkel** [comment]
Ok. On my way
