### ISSUE TITLE
Email Addresses for Reminders

### ISSUE THREAD

**Issue by JanGVoelkel** [chartgerink/2015ori#20]
Just wondering/doublechecking whether we have the appropriate information (names and email addresses) for sending out the reminders? We checked that today in case I cannot find a date for the meeting, but for the reminders I have already accepted the date.

We have the email addresses from the sampling frame, but not sure whether we can (want to be able to) match them with the appointments.

**Comment by chartgerink** [comment]
I just sent you some suggestions at Doodle. If you accept, check if you can send messages to the respondent via doodle or get their email.

For the appointments, they are just in your calendar. You need to delete these from your calendar once we've finished data collection.

**Comment by JanGVoelkel** [comment]
Can't send them messages (except for cancelling the meeting) or get their emails
