### ISSUE TITLE
Cleaning up after the interviews

### ISSUE THREAD

**Issue by JanGVoelkel** [chartgerink/2015ori#29]
Need to be deleted
- [x] Qualtrics data (location and email-address)
- [x] Email conversations with participants
- [x] Interview schedule excel file (including location, email-address)

**Comment by JanGVoelkel** [comment]
Chris, please comment on whether you agree with the division regarding deletion or putting on stick.
And feel free to add things that come to your mind.

**Comment by chartgerink** [comment]
Any updates on this @Janto91?

**Comment by JanGVoelkel** [comment]
As many asked for an update with the results, shall we send an email whose email address we should keep for emailing them the final paper?

**Comment by chartgerink** [comment]
We have to send the results to all invited participants anyway (i.e., in the sampling frame; tell you more about it during lunch) so no need to keep these separately.

**Comment by chartgerink** [comment]
Feel free to close this once you've deleted the Qualtrics project (added the Qualtrics files in commit 4b6a4225eb7db35861f7809a20df1b9cf21bc393)
