### ISSUE TITLE
Transcripts planning

### ISSUE THREAD

**Issue by chartgerink** [chartgerink/2015ori#34]
- [x] 21st april - 3 transcripts
- [x] 28th april - 3 transcripts
- [x] 5th may - 3 transcripts
- [x] 12th may - 3 transcripts
- [x] 19th may - 2 transcripts
- [x] 26th may - 2 transcripts
- [x] 2nd june - 2 transcripts
- [x] 9th june - 2 transcripts
- [x] 16th june - 2 transcripts
- [x] 23rd june - 2 transcripts
- [x] 30th june - 2 transcripts

@Janto91 please indicate when you've done which one. That way I don't have to e-mail you to ask how things are going each week 😉

**Comment by chartgerink** [comment]
@Janto91 how are things going? I have yet to read through the recent three but it seems like you are one week behind at the moment so I'm checking in.

**Comment by JanGVoelkel** [comment]
Well, I am working on the three for this week (I often still need the weekend to finish it (and I was gone last weekend which is why it took a bit longer for the 3 last week) but I think I will be done with no. 12-14 this weekend

**Comment by chartgerink** [comment]
All transcripts done and merged in #40
