### ISSUE TITLE
Tasks for Week 3.10.-9.10.

### ISSUE THREAD

**Issue by JanGVoelkel** [chartgerink/2015ori#8]
## Chris
- [x] Bring dictaphone to next meeting
- [ ] Bring USB to next meeting
- [x] Check with finance what information they need for receipts
- [ ] Ask for the advance
- [x] Check the software for transcription
- [x] Review the sampling frame
- [ ] Send Jan papers
## Jan
- [x] Come up with questions for interviews: Add to Chris' suggestions
- [x] Add instructions on my doodle page (in the overview, not on the doodle page itself)
- [x] Work on step-by-step protocol for after interview (how it is shared (Surfdrive), how we ensure anonymity)
- [x] Write down steps for interview
- [x] Set a quota on qualtrics (no more than 20): Add variable whether they were able to find timeslots so that it can be linked
- [x] Play around with R Markdown (dynamic figure, table, result in running text, citation)
- [ ] Read through papers that Chris sends me

**Comment by chartgerink** [comment]
Let's go with [oTranscribe](http://otranscribe.com/). Many of the software applications have low recognition rates (20-25% for CMUSphinx by default; have to built different use-case to up it), so in the end we would have to check anyway. 

It'll take some effort but it will definitely be better than straight out transcribing using VLC or so. The timestamping from oTranscribe will also help and they are easily exported to Markdown files.

**Comment by JanGVoelkel** [comment]
Ok!
